name: EssayHelper
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.114
  - blas-devel=3.9.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cryptography=36.0.2
  - cudatoolkit=10.2.89
  - ffmpeg=4.3
  - freetype=2.10.4
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - idna=3.3
  - jbig=2.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=14.0.3
  - lz4-c=1.9.3
  - mkl=2022.0.1
  - mkl-devel=2022.0.1
  - mkl-include=2022.0.1
  - ncurses=6.3
  - nettle=3.6
  - numpy=1.22.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - pillow=9.1.0
  - pip=22.0.4
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.1
  - requests=2.27.1
  - setuptools=62.1.0
  - sqlite=3.38.3
  - tbb=2021.5.0
  - tk=8.6.12
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - urllib3=1.26.9
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - beautifulsoup4==4.11.1
    - blessings==1.7
    - classla==1.1.0
    - click==8.1.3
    - curtsies==0.3.10
    - cwcwidth==0.1.6
    - cycler==0.11.0
    - cython==0.29.30
    - decorator==5.1.1
    - enum34==1.1.10
    - filehash==0.2.dev1
    - filelock==3.6.0
    - flask==2.1.2
    - fonttools==4.33.3
    - gpy==1.10.0
    - gpyopt==1.2.6
    - huggingface-hub==0.5.1
    - importlib-metadata==4.11.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.1.0
    - kiwisolver==1.4.3
    - lxml==4.8.0
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - obeliks==1.1.4
    - packaging==21.3
    - pandas==1.4.2
    - parameter-sherpa==1.0.6
    - paramz==0.9.5
    - protobuf==3.20.1
    - psutil==5.9.1
    - pymongo==4.1.1
    - pyparsing==3.0.8
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.4.24
    - reldi-tokeniser==1.0.1
    - sacremoses==0.0.49
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - stanza==1.2
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - toma==1.1.0
    - tqdm==4.64.0
    - transformers==4.20.0
    - werkzeug==2.1.2
    - zipp==3.8.0
